.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DS" "1" "July 2017" "dashohoxha" "DockerScripts"
.
.SH "NAME"
\fBds\fR \- Docker Scripts
.
.SH "SYNOPSIS"
\fBds\fR \fICOMMAND\fR
.
.SH "DESCRIPTION"
DockerScripts is a shell script framework for Docker which simplifies managing containers in a context\. Each container is like a virtual machine that has an application installed inside\. Each container has a base directory where the settings of the container are stored (in the file \fIsettings\.sh\fR)\. The command \fBds\fR picks the parameters that it needs from the file \fIsettings\.sh\fR in the current directory\.
.
.SH "COMMANDS"
.
.IP "\(bu" 4
\fBinit\fR \fI\fIsrc_dir\fR\fR, \fBinfo\fR
.
.IP
Initialize a working directory by getting the file \fIsettings\.sh\fR from the given source directory\. Show some of the current settings\.
.
.IP "\(bu" 4
\fBbuild\fR, \fBcreate\fR, \fBconfig\fR
.
.IP
Build the image, create the container, and configure the guest system inside the container\.
.
.IP "\(bu" 4
\fBstart\fR, \fBstop\fR, \fBrestart\fR
.
.IP
Start, stop and restart the container\.
.
.IP "\(bu" 4
\fBshell\fR
.
.IP
Get a shell on the container\.
.
.IP "\(bu" 4
\fBexec\fR
.
.IP
Execute a command inside the container\.
.
.IP "\(bu" 4
\fBsnapshot\fR
.
.IP
Make a snapshot of the container\.
.
.IP "\(bu" 4
\fBremove\fR
.
.IP
Remove the container and the image\.
.
.IP "\(bu" 4
\fBhelp\fR
.
.IP
Display a help message\.
.
.IP "" 0
.
.SH "FILES"
\fB\./settings\.sh\fR
.
.IP "" 4
.
.nf

      It is located in directory of the container and keeps the
      settings of the container and the settings of the
      application installed inside it\.
.
.fi
.
.IP "" 0
.
.SH "CUSTOMIZATION"
The file \fB$SRC/ds\.sh\fR or \fB\./ds\.sh\fR can be used to redefine and customize some functions, without having to touch the code of the main script\. Also, custom commands can be defined for each container type and for each container in the file \fB$SRC/cmd/command\.sh\fR or \fB\./cmd/command\.sh\fR, which should contain the function \fBcmd_command() { \. \. \. }\fR\. If the name of a defined command is the same as an existing command, it overrides the existing one\.
.
.SH "INSTALLATION"
.
.nf

git clone https://github\.com/docker\-scripts/ds /usr/local/src/ds
cd /usr/local/src/ds/
make install
ds help
.
.fi
.
.SH "USAGE"
Some examples of using \fBds\fR are shown below\.
.
.SS "Installing Moodle"
.
.nf

git clone https://github\.com/docker\-scripts/moodle /usr/local/src/moodle
mkdir \-p /var/containers/moodle1
cd /var/containers/moodle1/
ds init /usr/local/src/moodle
vim settings\.sh
ds build
ds create
ds config
ds shell
.
.fi
.
.SH "AUTHOR"
Copyright (C) 2017 Dashamir Hoxha (dashohoxha@gmail\.com)\. The code is on GitHub at \fIhttps://github\.com/dashohoxha/ds\fR\.
.
.SH "COPYLEFT"
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\.
.
.P
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\. See the GNU General Public License for more details\.
.
.P
You should have received a copy of the GNU General Public License along with this program\. If not, see \fIhttp://www\.gnu\.org/licenses/\fR\.
